import Head from 'next/head'
import Router from 'next/router';
import { Mode, useRouterMode } from '../RouterModeContext/RouterModeContext'
import styles from './Layout.module.css'
import { useMemo } from 'react'

export function Layout({ title, children }) {
  const navigation = useNavigation();

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navigation}>
        <button className={styles.button} onClick={navigation.back}>{'<'} 뒤로</button>
        <button className={styles.button} onClick={() => location.href = '/'}>HOME</button>
        <button className={styles.button} onClick={navigation.forward}>앞으로 {'>'}</button>
      </div>

      <div className={styles.container__inner}>
        {children}
      </div>
    </div>
  )
}

function useNavigation() {
  const { mode } = useRouterMode();

  return useMemo(() => {
    if (mode === Mode.Native) {
      return {
        back: () => history.back(),
        forward: () => history.forward(),
      }
    }

    return {
      back: () => Router.back(),
      forward: () => history.forward(),
    }
  }, [mode])
}