import Head from 'next/head'
import styles from './Layout.module.css'

export function Layout({ title, children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout.Navigation />

      <div className={styles.container__inner}>
        {children}
      </div>
    </div>
  )
}

Layout.Navigation = function Navigation() {
  return (
    <div className={styles.navigation}>
      <button className={styles.button} onClick={() => history.back()}>{'<'} 뒤로</button>
      <button className={styles.button} onClick={() => history.forward()}>앞으로 {'>'}</button>
    </div>
  )
}